/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/discobolus.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function DiscobolousModel(props) {
  const { nodes, materials } = useGLTF("/discobolus.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.empty_2.geometry}
        material={nodes.empty_2.material}
      />
    </group>
  );
}

useGLTF.preload("/discobolus.glb");
