/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/discobolus.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function DiscobolousModel(props) {
  const { nodes, materials } = useGLTF("/discobolus.glb");

  const statref = useRef();

  useFrame((state, delta) => {
    if (statref.current) {
      statref.current.rotation.z += delta * 0.5;
    }
  });

  return (
    <group ref={statref} {...props} dispose={null}>
      <mesh
        geometry={nodes.empty_2.geometry}
        material={nodes.empty_2.material}
      />
    </group>
  );
}

useGLTF.preload("/discobolus.glb");
